<template>
    <div>
        数据管理
        <div>1-a</div>
        <div>2-a</div>
        <div>3-a</div>
        <div>4-a</div>
        <div>5-a</div>
        <div>6-a</div>
        <div>7-a</div>
        <div>8-a</div>
        <div>9-a</div>
        <div>10-a</div>
        <div>11-a</div>
        <div>12-a</div>
        <div>13-a</div>
        <div>14-a</div>
        <div>15-a</div>
        <div>16-a</div>
        <div>17-a</div>
        <div>18-a</div>
        <div>19-a</div>
        <div>20-a</div>
        <div>21-a</div>
        <div>22-a</div>
        <div>23-a</div>
        <div>24-a</div>
        <div>25-a</div>
        <div>26-a</div>
        <div>27-a</div>
        <div>28-a</div>
        <div>29-a</div>
        <div>30-a</div>
        <div>31-a</div>
        <div>32-a</div>
        <div>33-a</div>
        <div>34-a</div>
        <div>35-a</div>
        <div>36-a</div>
        <div>37-a</div>
        <div>38-a</div>
        <div>39-a</div>
        <div>40-a</div>
        <div>41-a</div>
        <div>42-a</div>
        <div>43-a</div>
        <div>44-a</div>
        <div>45-a</div>
        <div>46-a</div>
        <div>47-a</div>
        <div>48-a</div>
        <div>49-a</div>
        <div>50-a</div>
        <div>51-a</div>
        <div>52-a</div>
        <div>53-a</div>
        <div>54-a</div>
        <div>55-a</div>
        <div>56-a</div>
        <div>57-a</div>
        <div>58-a</div>
        <div>59-a</div>
        <div>60-a</div>
        <div>61-a</div>
        <div>62-a</div>
        <div>63-a</div>
        <div>64-a</div>
        <div>65-a</div>
        <div>66-a</div>
        <div>67-a</div>
        <div>68-a</div>
        <div>69-a</div>
        <div>70-a</div>
        <div>71-a</div>
        <div>72-a</div>
        <div>73-a</div>
        <div>74-a</div>
        <div>75-a</div>
        <div>76-a</div>
        <div>77-a</div>
        <div>78-a</div>
        <div>79-a</div>
        <div>80-a</div>
        <div>81-a</div>
        <div>82-a</div>
        <div>83-a</div>
        <div>84-a</div>
        <div>85-a</div>
        <div>86-a</div>
        <div>87-a</div>
        <div>88-a</div>
        <div>89-a</div>
        <div>90-a</div>
        <div>91-a</div>
        <div>92-a</div>
        <div>93-a</div>
        <div>94-a</div>
        <div>95-a</div>
        <div>96-a</div>
        <div>97-a</div>
        <div>98-a</div>
        <div>99-a</div>
        <div>100-a</div>
    </div>
</template>

<script>
    export default {
        data() {
            return {

            };
        },
        methods: {

        }
    };
</script>

<style lang="less" scoped>

</style>
